# Generated by Django 4.2.3 on 2023-08-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("turn", "0002_appointment_patent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.patent",
            ),
        ),
    ]
