# Generated by Django 4.2 on 2023-08-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing', models.CharField(max_length=255)),
                ('codeID', models.CharField(max_length=11)),
                ('firstname', models.CharField(max_length=11)),
                ('lastname', models.CharField(max_length=11)),
                ('start_time', models.TimeField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
